### ISSUE TITLE
인스턴스 초기화 오류 

### ISSUE THREAD

**Issue by cherrytomato1** [cherrytomato1/Cloudy#5]
ava.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window$Callback android.view.Window.getCallback()' on a null object reference

해당 에러는 인스턴스를 초기화할 수 없는 장소 (method 외부)에서 초기화 시
런타임 에러 출력되면서 발생한다

이를 위해서 초기화 부분을 메소드 내로 옮기고 lateinit 키워드를 변수 선언 시 사용하여
나중에 초기화 될 수 있도록 지정하거나, 선언을 메소드 내부에서 해준다.

**Comment by gilyeon** [comment]
good job!

**Comment by wjrmffldrhrl** [comment]
good!
